### ISSUE TITLE
how to add runtime build_dir path 

### ISSUE THREAD

**Issue by okan-erdogan** [apkatsikas/xctest_pxctest_distributed#1]
Hi 
I am new in python
I am trying to run test using this approach. Every time i run xcode_build comand it generates xctestrun file under  /Users/userfolder/Library/Developer/Xcode/DerivedData/project-xxxxxxxxxxxxx/Build/Product
how can i store this path in runtime and use it later. (In this case it is BUILD_DIR in xcode environment variable)

**Comment by apkatsikas** [comment]
Hi @okanerdogan84! I noticed these files generating as well and have not yet interacted with them. 

You could create another command to execute in ios_tests.json that looks something like this:

`xcodebuild -project project.xcodeproj -target "project_target" -showBuildSettings | grep -w 'BUILD_DIR'`

to print out the build dir and then store it as a variable. let me know if you need more detailed instructions on how to handle this...

This article may be helpful for you - http://stackoverflow.com/questions/7279141/how-can-i-safely-delete-in-my-library-developer-xcode-deriveddata-directory

What you are trying to do with this data/folder?

**Comment by apkatsikas** [comment]
If you are trying to clear the data out, it should be safe to do so at the the parent folder level - 

http://stackoverflow.com/questions/18933321/can-i-safely-delete-contents-of-xcode-derived-data-folder

`alias purgeallbuilds='rm -rf ~/Library/Developer/Xcode/DerivedData/*'`

**Comment by okan-erdogan** [comment]
no i am not trying to delete it.
`--testrun %s/build/Products/\"project_iphonesimulator10.2-x86_64.xctestrun\`  i have to change this part of code because it is not generated in workspace for my project instead in /Users/userfolder/Library/Developer/Xcode/DerivedData/project-xxxxxxxxxxxxx/Build/Product    which generated randomly

**Comment by apkatsikas** [comment]
it sounds like there may be a misconfiguration in your project.

that should be generated in the directory specified in "directory" parameter on ios_tests.json, like this

`{directory}/build/Products/...`

The other thing to consider, is to grab the string of the .xctestrun file in derived data, and replace the string in your .json file with that...

Is it possible you could share your ios_tests.json file with me? Perhaps through email if you prefer it to here...

**Comment by apkatsikas** [comment]
@okanerdogan84  - did this answer your question?

**Comment by okan-erdogan** [comment]
one question more 
i want to run two different test target on different simulators how should i modify part below
--only 'Target1:Target2' 
my bad i understand now thanks

**Comment by apkatsikas** [comment]
Ah good question, i designed this to only use 1 target but it should be
easily modifiable... are you just looking to test 2 targets, 1 on each
simulator?
