### ISSUE TITLE
how to get results of execution

### ISSUE THREAD

**Issue by okan-erdogan** [apkatsikas/xctest_pxctest_distributed#2]
hi 
Do you have any idea about how to get total fails after running tests.
What we want to do is running tests parallel, check if all passed. if all passed trigger deploy boot.

**Comment by apkatsikas** [comment]
Hi @okanerdogan84 

There are a number of ways you could accomplish this.

Ultimately, you want to check the output of the Popen process.

See line 81 of https://github.com/apkatsikas/xctest_pxctest_distributed/blob/master/ios_parallel.py
Probably would modify this code

`    processes = [Popen(cmd, cwd=REPO_DIRECTORY, shell=True) for cmd in commands_param]
    for p in processes:
        p.wait()
`

Try searching for examples of "Popen get output" - like below:

http://stackoverflow.com/questions/2502833/store-output-of-subprocess-popen-call-in-a-string

You could parse the results of the output and look for instances of "fail" etc...

Let me know if you have further questions on this.

**Comment by okan-erdogan** [comment]
thanks code below worked for me
`out=p.stdout.read()
        out2=sys.stdout.write(out)
        temps = str(out).split('Total')[1]
        if "Failures" in temps:
          numberOfFails = temps.split('tests.')[1].split(' ')[1]
          numberOfTotalFail += int(numberOfFails)
        sys.stdout.flush()`

**Comment by apkatsikas** [comment]
great stuff @okanerdogan84 ! let me know if you have more questions, i will be closing this out.
