### ISSUE TITLE
some how boot simulator command sticks and generates files again

### ISSUE THREAD

**Issue by okan-erdogan** [apkatsikas/xctest_pxctest_distributed#3]
After running build_simulator command i see ~/sim_device/1 folder is generated. But after tests finished when i delete this file i see that it is generated again.Some how it is sticked and generates files again and again. How can I prevent that?

**Comment by apkatsikas** [comment]
@okanerdogan84  - this is an issue i have witnessed as well, and i am not entirely sure of why it happens. deleting the whole workspace folder a few seconds before a run seems to do the trick for me.

**Comment by apkatsikas** [comment]
@okanerdogan84  - if you need to make this automated, try clearing out the directory before your tests begin at the start of the script.
